import React, { Component } from 'react';
import { render } from 'react-dom';
import _set from 'lodash/fp/set';

import Hagrid, {
  Input,
  Select,
  withKeyEvents,
  withCheckboxColumn
} from '../../src';

const KeyHagrid = withCheckboxColumn(withKeyEvents(Hagrid));
class Demo extends Component {
  constructor() {
    super();
    this.columns = [
      {
        Header: 'ID',
        Cell: row => <span>{row.index + 1}</span>,
        className: 'font-weight-normal',
        width: 40
      },
      {
        Header: <span>Soil Depth</span>,
        accessor: 'input.depth',
        headerClassName: 'editable',
        className: 'editable',
        width: 90,
        Cell: (row, { isFocused }) => (
          <Input
            type="number"
            isFocused={isFocused}
            id={row.original.id}
            name="input.depth"
            value={row.value}
            handleChange={this.handleChange}
          />
        )
      },
      {
        Header: 'Soil Type',
        accessor: 'input.soilType',
        headerClassName: 'editable',
        className: 'editable selectable',
        width: 100,
        Cell: (row, { isFocused, onEnter }) => (
          <Select
            searchable
            id={row.original.id}
            isFocused={isFocused}
            name="input.soilType"
            value={row.value}
            noResultsText="No data found"
            handleChange={this.handleChange}
            onEnter={onEnter}
            options={[
              {
                label: '1',
                value: '1'
              },
              {
                label: '2',
                value: '2'
              }
            ]}
          />
        )
      },
      {
        Header: 'NF',
        accessor: 'input.blowCount',
        headerClassName: 'editable',
        className: 'editable',
        width: 40,
        Cell: (row, { isFocused }) => (
          <Input
            isFocused={isFocused}
            id={row.original.id}
            name="input.blowCount"
            value={row.value}
            handleChange={this.handleChange}
          />
        )
      },
      {
        Header: 'Const',
        accessor: 'input.const',
        headerClassName: 'editable',
        className: 'editable',
        width: 50,
        Cell: (row, { isFocused }) => (
          <Input
            isFocused={isFocused}
            id={row.original.id}
            name="input.const"
            value={row.value}
            handleChange={this.handleChange}
          />
        )
      },
      {
        Header: '%fines',
        accessor: 'input.percentFines',
        headerClassName: 'editable',
        className: 'editable',
        width: 50,
        Cell: (row, { isFocused }) => (
          <Input
            isFocused={isFocused}
            id={row.original.id}
            name="input.percentFines"
            value={row.value}
            handleChange={this.handleChange}
          />
        )
      },
      {
        Header: 'MC',
        accessor: 'input.MC',
        headerClassName: 'editable',
        className: 'editable',
        width: 40,
        Cell: (row, { isFocused }) => (
          <Input
            isFocused={isFocused}
            id={row.original.id}
            name="input.MC"
            value={row.value}
            handleChange={this.handleChange}
          />
        )
      },
      {
        Header: 'LL',
        accessor: 'input.LL',
        headerClassName: 'editable',
        className: 'editable',
        width: 40,
        Cell: (row, { isFocused }) => (
          <Input
            name="input.LL"
            isFocused={isFocused}
            id={row.original.id}
            value={row.value}
            handleChange={this.handleChange}
          />
        )
      },
      {
        Header: "E's (kPa)",
        accessor: 'calculated.ESinKPA',
        width: 100
      },
      {
        Header: "E's (psf)",
        accessor: 'calculated.ESinPSF',
        width: 100
      },
      {
        Header: 'Elevation (ft)',
        accessor: 'calculated.elevation',
        width: 75
      },
      {
        Header: 'CN',
        accessor: 'calculated.overburdenCorrectionFactor_CN',
        width: 50
      },
      {
        Header: 'N1-60',
        accessor: 'calculated.N160',
        width: 100
      },
      {
        Header: 'N1-60(CS)',
        accessor: 'calculated.N160_CS',
        width: 100
      },
      {
        Header: 'Constrained Modulus',
        accessor: 'calculated.constrainedModulus',
        width: 100
      }
    ];
    this.state = {
      selections: [],
      data: {
        '1': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '5',
            cohesion: '',
            comments: '',
            soilType: 'OM',
            blowCount: 10,
            percentFines: 0,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 90.19,
            depth: 5,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 95,
            totalStress_SVo: null,
            currentUnitWeight: 90.19,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '2': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '10',
            cohesion: '',
            comments: '',
            soilType: 'OM',
            blowCount: 10,
            percentFines: 0,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 90.19,
            depth: 10,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 90,
            totalStress_SVo: null,
            currentUnitWeight: 90.19,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '3': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '15',
            cohesion: '',
            comments: '',
            soilType: 'OM',
            blowCount: 10,
            percentFines: 0,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 90.19,
            depth: 15,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 85,
            totalStress_SVo: null,
            currentUnitWeight: 90.19,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '4': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '20',
            cohesion: '',
            comments: '',
            soilType: 'GW',
            blowCount: 25,
            percentFines: 3,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 90.19,
            depth: 20,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 80,
            totalStress_SVo: null,
            currentUnitWeight: 90.19,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '5': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '25',
            cohesion: '',
            comments: '',
            soilType: 'GW',
            blowCount: 25,
            percentFines: 3,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 90.19,
            depth: 25,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 75,
            totalStress_SVo: null,
            currentUnitWeight: 90.19,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '6': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '30',
            cohesion: '',
            comments: '',
            soilType: 'GW',
            blowCount: 25,
            percentFines: 3,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 90.19,
            depth: 30,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 70,
            totalStress_SVo: null,
            currentUnitWeight: 90.19,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '7': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '35',
            cohesion: '',
            comments: '',
            soilType: 'GM',
            blowCount: 25,
            percentFines: 15,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 125.89,
            depth: 35,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 65,
            totalStress_SVo: null,
            currentUnitWeight: 125.89,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '8': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '40',
            cohesion: '',
            comments: '',
            soilType: 'GM',
            blowCount: 30,
            percentFines: 15,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 128.44,
            depth: 40,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 60,
            totalStress_SVo: null,
            currentUnitWeight: 128.44,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '9': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '45',
            cohesion: '',
            comments: '',
            soilType: 'GM',
            blowCount: 30,
            percentFines: 15,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 128.44,
            depth: 45,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 55,
            totalStress_SVo: null,
            currentUnitWeight: 128.44,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '10': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '50',
            cohesion: '',
            comments: '',
            soilType: 'SP',
            blowCount: 40,
            percentFines: 3,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 134.95,
            depth: 50,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 50,
            totalStress_SVo: null,
            currentUnitWeight: 134.95,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '11': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '55',
            cohesion: '',
            comments: '',
            soilType: 'SP',
            blowCount: 40,
            percentFines: 3,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 134.95,
            depth: 55,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 45,
            totalStress_SVo: null,
            currentUnitWeight: 134.95,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '12': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '60',
            cohesion: '',
            comments: '',
            soilType: 'SP',
            blowCount: 40,
            percentFines: 3,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 134.95,
            depth: 60,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 40,
            totalStress_SVo: null,
            currentUnitWeight: 134.95,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '13': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '65',
            cohesion: '',
            comments: '',
            soilType: 'SP',
            blowCount: 40,
            percentFines: 3,
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: 134.95,
            depth: 65,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: 35,
            totalStress_SVo: null,
            currentUnitWeight: 134.95,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '14': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '15': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '16': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '17': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '18': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '19': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '20': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '21': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '22': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '23': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '24': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '25': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '26': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '27': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '28': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '29': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '30': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '31': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '32': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '33': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '34': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '35': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '36': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '37': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '38': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '39': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '40': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '41': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '42': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '43': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '44': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '45': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '46': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '47': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '48': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '49': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        },
        '50': {
          input: {
            LL: '',
            MC: '',
            PL: '',
            const: '',
            depth: '',
            cohesion: '',
            comments: '',
            soilType: '',
            blowCount: '',
            percentFines: '',
            compressionIndex: '',
            currentUnitWeight: '',
            recompressionIndex: '',
            preConsolidationPressure: ''
          },
          override: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          },
          calculated: {
            N160: null,
            deltaN: null,
            ESinKPA: null,
            ESinPSF: null,
            N160_CS: null,
            elevation: null,
            totalStress_SVo: null,
            currentUnitWeight: null,
            constrainedModulus: null,
            effectiveStress_ESVO: null,
            linerCorrectionFactor_CS: null,
            energyCorrectionFactor_CE: null,
            boreholeCorrectionFactor_CB: null,
            rodLengthCorrectionFactor_CR: null,
            overburdenCorrectionFactor_CN: null
          }
        }
      }
    };
  }

  setSelections = selections => {
    this.setState({
      selections
    });
  };

  handleChange = (id, name, value) => {
    let { data } = this.state;

    this.setState({
      data: {
        ...data,
        [id]: _set(name)(value)(data[id])
      }
    });
  };

  render() {
    const { data } = this.state;
    let rows = Object.keys(data)
      .sort((a, b) => a - b)
      .reduce(
        (acc, next) =>
          acc.concat({
            ...data[next],
            id: next
          }),
        []
      );

    return (
      <div>
        <h1>React Sheet</h1>
        <KeyHagrid
          data={rows}
          height={500}
          columns={this.columns}
          handleChange={this.handleChange}
          setSelections={this.setSelections}
          selections={this.state.selections}
        />
      </div>
    );
  }
}

render(<Demo />, document.querySelector('#demo'));
